version: "3.1"
services:
  web:
    image: odoo:16
    container_name: web-odoo-machine-maintenance
    depends_on:
      - db
    volumes:
      - odoo-web-data-machine-maintenance:/var/lib/odoo
      - ./config:/etc/odoo
      - ./local-addons:/mnt/extra-addons
    environment:
      - USER=odoo
      - PASSWORD=odoo
    networks:
      - odoo-machine-maintenance
  db:
    image: postgres:13
    container_name: db-odoo-machine-maintenance
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data-machine-maintenance:/var/lib/postgresql/data/pgdata
    networks:
      - odoo-machine-maintenance
  pgadmin:
    container_name: pgadmin-odoo-machine-maintenance
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: amdin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin-machine-maintenance:/var/lib/pgadmin
    ports:
      - 5433:80
    networks:
      - odoo-machine-maintenance
    restart: unless-stopped
  proxy:
    depends_on:
            - web
    container_name: odoo_proxy-machine-maintenance
    build:
        context: .
        dockerfile: Dockerfile-nginx
    ports:
        - "8069:8069"
    networks:
      - odoo-machine-maintenance

networks:
  odoo-machine-maintenance:
    driver: bridge


volumes:
  odoo-web-data-machine-maintenance:
  odoo-db-data-machine-maintenance:
  pgadmin-machine-maintenance:
